renegade-fi/rust-sdk

Cargo.toml, README.md
This PR fixes the `renegade-auth-api` dependency to use the git source
=> chore: use git instead of local dep

Cargo.toml, src/external_match_client/mod.rs
This PR updates the SDK to support both base and quote amounts in an `ExternalOrder` specification.
=> external-match-client: Add support for both base and quote amounts

Cargo.toml, examples/external_match/modify_order_after_quote.rs, src/external_match_client/client.rs, src/external_match_client/mod.rs
This PR allows order updates in between quote and assembly in the rust SDK. The `base_amount`, `quote_amount`, and `min_fill_size` fields are all allowed to change.
I also added an example [`examples/modify_order_after_quote`](./examples/modify_order_after_quote.rs) which demonstrates this.
=> external-match-client: Allow order updates in quote assembly

Cargo.toml, src/external_match_client/client.rs, src/external_match_client/mod.rs
This PR adds gas sponsorship options to direct match and quote assembly options.
=> external-match-client: Add options for gas sponsorship

Cargo.toml, examples/external_match/gas_sponsorship.rs
This PR adds an example for using gas sponsorship in assembling an external match
=> examples: external-match: Add gas sponsorship example

Cargo.toml, examples/external_match/supported_tokens.rs, src/external_match_client/client.rs
This PR adds a supported tokens method and example for fetching the token address of WETH
=> external-match-client: Add supported tokens method

examples/external_match/external_match.rs, examples/external_match/gas_sponsorship.rs, examples/external_match/modify_order_after_quote.rs, examples/external_match/non_sender_receiver.rs, examples/external_match/quote_validation.rs, src/external_match_client/api_types.rs, src/external_match_client/client.rs, src/external_match_client/mod.rs
This PR adds the `gas_sponsored` flag to the response received by the client for assembling quotes.
=> external-match-client: api-types: Add `gas_sponsored` flag

Cargo.toml, examples/external_match/external_match.rs, examples/external_match/gas_sponsorship.rs, examples/external_match/modify_order_after_quote.rs, examples/external_match/non_sender_receiver.rs, examples/external_match/quote_validation.rs, src/example_utils.rs, src/external_match_client/api_types.rs, src/external_match_client/client.rs, src/external_match_client/mod.rs, src/http.rs, src/lib.rs, src/types.rs, src/util.rs
This PR internalizes the API types used in the external match client to reduce the number of dependencies in the client.
=> external-match-client: Internalize API types

.gitignore, src/external_match_client/api_types.rs, src/external_match_client/client.rs, src/external_match_client/mod.rs
This PR enables support for in-kind gas sponsorship.
- Update / new examples
=> external_match_client: api_types, client: support in-kind sponsorship

Cargo.toml, README.md, examples/external_match/in_kind_gas_sponsorship.rs, examples/external_match/native_eth_gas_sponsorship.rs, src/external_match_client/client.rs, src/external_match_client/mod.rs
This PR updates the existing gas sponsorship example to focus in on native ETH refunds, and adds an example for in-kind gas sponsorship. Both of these examples run as expected.
=> examples: external_match: update gas sponsorship ex & add in-kind ex

src/external_match_client/client.rs
This PR adds compiler deprecation warnings when trying to set gas sponsorship parameters on the `AssembleQuoteOptions` struct
=> external_match_client: client: add deprecation warnings for gas sponsorship during assembly

Cargo.toml, examples/external_match/in_kind_gas_sponsorship.rs, src/external_match_client/api_types.rs, src/external_match_client/client.rs
This PR removes the `gas_sponsorship_info` field from the `AssembleExternalMatchRequest`, as this is no longer needed by the API.
=> external_match_client: api_types: remove sponsorship info from assembly request

Cargo.toml, README.md, examples/external_match/shared_bundle.rs, src/external_match_client/api_types.rs, src/external_match_client/client.rs
This PR adds the `allow_shared` option to the assemble options in the SDK and adds an example using the `allow_shared` flag.
=> external-match-client: api-types, client: Expose `allow_shared` option

Cargo.toml, examples/external_match/external_match.rs, examples/external_match/in_kind_gas_sponsorship.rs, examples/external_match/malleable_match.rs, examples/external_match/modify_order_after_quote.rs, examples/external_match/native_eth_gas_sponsorship.rs, examples/external_match/non_sender_receiver.rs, examples/external_match/quote_validation.rs, examples/external_match/shared_bundle.rs, src/example_utils.rs, src/external_match_client/api_types/fixed_point.rs, src/external_match_client/api_types/mod.rs, src/external_match_client/api_types/order_types.rs, src/external_match_client/api_types/request_response.rs, src/external_match_client/client.rs
This PR adds an SDK method for assembling a quote into a malleable match. I added an example which does so without setting the base amount -- which is defaulted to the max base amount.
- Add methods for setting the base amount conveniently in the calldata, as well as computing receive amount, send amount, and fees.
=> external-match-client: Add methods for malleable matches

Cargo.toml, README.md, examples/external_match/malleable_match.rs, src/external_match_client/api_types/fixed_point.rs, src/external_match_client/api_types/malleable_match.rs, src/external_match_client/api_types/mod.rs, src/external_match_client/api_types/order_types.rs, src/external_match_client/api_types/request_response.rs, src/external_match_client/error.rs
This PR adds helpers for setting the base amount in a malleable match, including helpers to compute the send and receive amounts given a counterfactual base amount. These helpers all include gas sponsorship and represent the "all in" price.
=> external-match-client: api-types: Add helpers for setting base amounts

src/external_match_client/api_types/malleable_match.rs
This PR changes the way in which we read and modify calldata for malleable matches to use the `tx.input()` method; which correctly handles both the case in which the calldata is specified as the `input` field and when it is specified as the `data` field.
=> external-match-client: malleable-match: Fix use of `data` field

Cargo.toml, examples/external_match/supported_tokens.rs, src/example_utils.rs, src/external_match_client/client.rs
This PR migrates the relayer & auth server URLs used by the external match client to the new, chain-specific ones. Additionally, we deprecated the existing arbitrum sepolia/one constructors in favor of new, aptly-named ones.
=> external_match_client: client: use chain-aware URLs

Cargo.toml, src/external_match_client/api_types/malleable_match.rs, src/external_match_client/api_types/order_types.rs, src/types.rs
This PR properly sets the `value` field on the settlement transaction to the base amount swapped in the case that a malleable match is a native ETH sell.
=> external-match-client: malleable-match: Fix `value` on native eth sell

Cargo.toml, examples/external_match/malleable_match.rs, src/example_utils.rs, src/external_match_client/api_types/fixed_point.rs, src/external_match_client/api_types/malleable_match.rs, src/external_match_client/api_types/request_response.rs, src/external_match_client/client.rs
This PR exposes a method for setting the quote amount on a malleable match, from which the base amount is derived. This comes with the necessary checks for validity of the quote amount, which mirror those in the contracts.
=> external_match_client: malleable_match: allow setting quote amount

Cargo.toml, examples/external_match/base_sepolia_match.rs, examples/external_match/external_match.rs, examples/external_match/in_kind_gas_sponsorship.rs, examples/external_match/malleable_match.rs, examples/external_match/modify_order_after_quote.rs, examples/external_match/native_eth_gas_sponsorship.rs, examples/external_match/quote_validation.rs, examples/external_match/shared_bundle.rs, src/example_utils.rs, src/external_match_client/client.rs
This PR adds Base client configs and an example using Base Sepolia to the rust SDK.
=> renegade: external-match-client: Add Base client configs

Cargo.toml, examples/order_book/order_book_depth.rs
This PR allows more permissive alloy versions, given that we don't use the alloy functionality unique to `>0.1.0`.
=> chore: Allow more permissive `alloy` versions

Cargo.toml
This PR allows a range of versions for the `reqwest` dependency to allow for different client pinned versions.
=> chore: Widen allowable `reqwest` versions

Cargo.toml, examples/order_book/all_pairs_depth.rs, src/external_match_client/api_types/order_book.rs, src/external_match_client/client.rs
This PR adds a helper method and example for calling `/v0/order_book/depth` to fetch book depth for all supported pairs.
=> external-match-client: Add all pairs book depth method

Cargo.toml, examples/wallet/create_wallet.rs, src/external_match_client/client.rs, src/lib.rs, src/renegade_wallet_client/actions/create_wallet.rs, src/renegade_wallet_client/actions/mod.rs, src/renegade_wallet_client/client.rs, src/renegade_wallet_client/mod.rs, src/util.rs
This PR adds a create wallet command to the wallet SDK and an example to test with.
=> renegade-wallet-client: Add create wallet command and example

Cargo.toml, examples/wallet/get_wallet.rs, src/renegade_wallet_client/actions/get_wallet.rs, src/renegade_wallet_client/actions/mod.rs, src/renegade_wallet_client/client.rs
This PR adds an action to get the back of queue wallet and return it to the user.
I also added an example for testing which prints wallet balances and orders.
=> renegade-wallet-client: actions: get-wallet: Add get wallet command

Cargo.toml, examples/wallet/place_order.rs, src/renegade_wallet_client/actions/get_wallet.rs, src/renegade_wallet_client/actions/mod.rs, src/renegade_wallet_client/actions/place_order.rs, src/renegade_wallet_client/mod.rs
This PR adds a `create_order` method to the wallet client as well as an `OrderBuilder` struct and an example creating a WETH sell order.
=> renegade-wallet-client: actions: create-order: Add create order command

Cargo.toml, examples/wallet/cancel_order.rs, src/renegade_wallet_client/actions/cancel_order.rs, src/renegade_wallet_client/actions/mod.rs, src/renegade_wallet_client/actions/place_order.rs
This PR adds a cancel order command to the darkpool and an example using this command.
=> renegade-wallet-client: actions: cancel-order: Add order cancellation

src/renegade_wallet_client/websocket/client.rs, src/renegade_wallet_client/websocket/task_waiter.rs
In this PR, we introduce reconnection logic to the `RenegadeWebsocketClient`. Previously, if the websocket connection was closed abruptly, the client would simply continue to attempt sending messages over the write end of the websocket stream and fail with `failed to send websocket message`. In fact, even in the case of graceful closure, the thread running the `handle_ws_connection` loop would simply join and the subscription channel's buffer would fill up with unhandled subscription requests.
Now, we wrap `handle_ws_connection` with the `ws_reconnection_loop` and propagate errors sending websocket messages, as they are indicative of websocket closures. When this (or graceful closure) occurs, a new websocket connection is established.
Additionally, we re-subscribe to all pending tasks …
=> renegade_wallet_client: websocket: reconnect to websocket upon closure
